### ISSUE TITLE
Make it responsive

### ISSUE THREAD

**Issue by Valentinbel** [labsforge/flipbook-ng#5]
Hello, 
I can't find how make it responsive. 
Can you help on this? 
Many thanks for your work.

**Comment by labsforge** [comment]
Hey! sorry late response..
It already supports, you need to calculate the view scale according the viewport you are using: https://github.com/labsforge/flipbook-ng/blob/8c7e55fe3ef21e3e8dab706458bafcf2a2deb1e0/projects/flipbook-app/src/app/app.component.ts#L114

**Comment by Valentinbel** [comment]
Hey, anoher question, 
Do you have any tricks to avoid this vertical white line between the two pages? 
(for example, this line appears in your flipbook_demo.gif).
Many thanks

**Comment by labsforge** [comment]
Pages are just divs with background images, the 3D transform on css probably doing this subpixel gaps, I think this is something I can't really fix... If you find any workaround, feel free to create a pull-request :)
